# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Nimish Singhal
title: Senior Frontent Developer
email: nimishsinghal188@gmail.com

darkmode: false

# Social links
linkedin_username: https://www.linkedin.com/in/nimish-singhal-abba6779
twitter_username: https://twitter.com/nimish_singhal
github_username:  https://github.com/nimishsinghal
instagram_username: https://www.instagram.com/nimish.singhal


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I am a frontend engineer based out of Bangalore, India. I have over 5 years of experience as web and mobile app developer.
  I am currently working for Flipkart as a frontend engineer on mobile website and apps. I love working on UI/UX, developing rich and innovative user interfaces that people love.

  I am a curious person who enjoys acquiring new knowledge. I collaborate with designers, product managers and backend developers to convert wireframes and low fidility prototypes into complete product.
  I have experience working on <mark>Javascript</mark>, <mark>CSS</mark>, <mark>HTML</mark> & <mark>Python</mark>. I have worked on following frameworks and libraries <mark>React & Redux</mark>, <mark>AngularJS</mark>, <mark>Webpack</mark>, <mark>Django</mark>, <mark>Express</mark>.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I am like any other "boring" software engineer who loves to watch movies, eat exciting food and travel to new destinations.
  I love to interact with new people, discuss interesting problems and find solutions to the unknowns.  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
